server:
  port: 80
spring:
  datasource:                                           # 数据源的相关配置        # 数据源类型：HikariCP
    url: jdbc:mysql://localhost:3306/foodie-shop?useSSL=false&useUnicode=true&characterEncoding=utf8
    password: root
  redis:
    database: 1
    host: 182.92.113.189
    port: 6379
    password: ls123456.